Repository HackYourFuture-CPH/fp-class20, pull requests merged in 2022-06, with the labels that each got.

#189 Add the toggle function back
  packages/client/src/components/ProductComponent/ProductCard.component.js
Labels: frontend

#190 Fixed to display the favorite page from 404 error page
  packages/client/src/App.js
  packages/client/src/containers/FavouritePage/FavouritePage.Container.js
Labels: frontend

#191 make the modal in the center
  packages/client/src/components/ProductComponent/ProductCardModal.styles.css
Labels: frontend

#188 fix-drop-down-arrow
  packages/client/public/assets/vectors/vector_arrow_down.svg
  packages/client/public/assets/vectors/vector_arrow_up.svg
  packages/client/src/components/SortBy/SortBy.component.js
  packages/client/src/components/SortBy/SortBy.styles.css
Labels: bug, frontend

#181 script/server: the easiest way to set up and run the project
  script/server
Labels: boilerplate

#146 Order page
  packages/client/src/App.js
  packages/client/src/Contexts/CartStateContext.js
  packages/client/src/components/DeliveryDetails/DeliveryDetails.component.js
  packages/client/src/components/DeliveryDetails/DeliveryDetails.styles.css
  packages/client/src/components/Order-Page/OrderPage.component.js
  packages/client/src/components/Order-Page/OrderPage.css
  packages/client/src/components/ShoppingCart/ProductComponent/OrderProduct.component.js
  packages/client/src/components/ShoppingCart/ShoppingCart.component.js
  packages/client/src/components/ShoppingCart/ShoppingCart.styles.css
  packages/client/src/components/ShoppingCart/Total/Total.js
  packages/client/src/components/TopNavBar/TopNavBar.component.js
Labels: frontend

#176 CLASS20-127 search product draft
  packages/client/src/App.js
  packages/client/src/components/BottomNavBar/Right-bottom-navigation/BottomNavigation.component.js
  packages/client/src/containers/SearchedProducts/SearchedProducts.Style.css
  packages/client/src/containers/SearchedProducts/SearchedProducts.js
  packages/server/api/controllers/products.controller.js
Labels: frontend

#195 Change props to use custome hook
  packages/client/src/components/ProductComponent/use_favorite_service.js
  packages/client/src/containers/FavouritePage/FavouritePage.Container.js
Labels: frontend

#194 fix css
  packages/client/src/components/ProductComponent/ProductCardModal.styles.css
  packages/client/src/components/ProductComponent/ProductCardVariant.styles.css
Labels: bug, frontend

#172 add sign in -sign out page
  packages/client/src/App.js
  packages/client/src/components/BottomNavBar/BottomNavBar.component.js
  packages/client/src/components/BottomNavBar/BottomNavBar.styles.css
  packages/client/src/components/Form/LoginSignupForm/LoginSignupForm.component.js
  packages/client/src/components/Form/LoginSignupForm/LoginSignupForm.styles.css
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Pagination/Pagination.js
  packages/client/src/components/SortBy/SortBy.component.js
  packages/client/src/components/TopNavBar/TopNavBar.component.js
  packages/client/src/components/TopNavBar/TopNavBar.styles.css
  packages/client/src/containers/LandingPage/ProductsList.js
  packages/client/src/containers/LoginPage/Login.Container.js
  packages/client/src/containers/LoginPage/Login.Styles.css
  packages/client/src/containers/SignupPage/Signup.Container.js
  packages/client/src/containers/SignupPage/Signup.Styles.css
Labels: frontend

#198 Number of items in ProductCardModal
  packages/client/src/components/ProductComponent/ProductCardModal.component.js
Labels: frontend

#197 make the amout of products appear in the modal
  packages/client/src/components/ProductComponent/ProductCard.component.js
Labels: frontend

#201 Second round deploy production
  Procfile
  packages/client/public/assets/vectors/vector_arrow_down.svg
  packages/client/public/assets/vectors/vector_arrow_up.svg
  packages/client/src/App.js
  packages/client/src/Contexts/CartStateContext.js
  packages/client/src/components/BottomNavBar/BottomNavBar.component.js
  packages/client/src/components/BottomNavBar/BottomNavBar.styles.css
  packages/client/src/components/BottomNavBar/Right-bottom-navigation/BottomNavigation.component.js
  packages/client/src/components/Carousel/Carousel.styles.css
  packages/client/src/components/Counter/Counter.styles.css
  packages/client/src/components/DeliveryDetails/DeliveryDetails.component.js
  packages/client/src/components/DeliveryDetails/DeliveryDetails.styles.css
  packages/client/src/components/Form/LoginSignupForm/LoginSignupForm.component.js
  packages/client/src/components/Form/LoginSignupForm/LoginSignupForm.styles.css
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Order-Page/OrderPage.component.js
  packages/client/src/components/Order-Page/OrderPage.css
  packages/client/src/components/Pagination/Pagination.js
  packages/client/src/components/Pagination/ProductLists.css
  packages/client/src/components/ProductComponent/ProductCard.component.js
  packages/client/src/components/ProductComponent/ProductCardModal.component.js
  packages/client/src/components/ProductComponent/ProductCardModal.styles.css
  packages/client/src/components/ProductComponent/ProductCardVariant.styles.css
  packages/client/src/components/ProductComponent/use_favorite_service.js
  packages/client/src/components/ShoppingCart/ProductComponent/OrderProduct.component.js
  packages/client/src/components/ShoppingCart/ShoppingCart.component.js
  packages/client/src/components/ShoppingCart/ShoppingCart.styles.css
  packages/client/src/components/ShoppingCart/Total/Total.js
  packages/client/src/components/SortBy/SortBy.component.js
  packages/client/src/components/SortBy/SortBy.styles.css
  packages/client/src/components/TopNavBar/TopNavBar.component.js
  packages/client/src/components/TopNavBar/TopNavBar.styles.css
  packages/client/src/containers/FavouritePage/FavouritePage.Container.js
  packages/client/src/containers/LandingPage/ProductsList.js
  packages/client/src/containers/LoginPage/Login.Container.js
  packages/client/src/containers/LoginPage/Login.Styles.css
  packages/client/src/containers/SearchedProducts/SearchedProducts.Style.css
  packages/client/src/containers/SearchedProducts/SearchedProducts.js
  packages/client/src/containers/SignupPage/Signup.Container.js
  packages/client/src/containers/SignupPage/Signup.Styles.css
  packages/server/api/controllers/products.controller.js
  packages/server/docker-compose.yml
  script/server
Labels: deployment
